# Generated by Django 5.1.5 on 2025-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWriter', '0004_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, to='BlogWriter.tag'),
        ),
    ]
