# Generated by Django 5.1.5 on 2025-09-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWriter', '0005_alter_userprofile_favorite_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
